import type { Milestone, Project, Task } from "@/types";

const now = "2026-09-05T06:00:00.000Z";

export const mockProjects: Project[] = [
  {
    id: "prj-hub",
    name: "Task Calendar Hub",
    color: "#3B82F6",
    status: "active",
    order: 1,
  },
  {
    id: "prj-client",
    name: "クライアント提案",
    color: "#8B5CF6",
    status: "active",
    order: 2,
  },
  {
    id: "prj-ops",
    name: "社内オペレーション",
    color: "#10B981",
    status: "active",
    order: 3,
  },
];

export const mockTasks: Task[] = [
  {
    id: "task-backlog-1",
    projectId: "prj-hub",
    title: "マイルストーンタイムラインのワイヤー",
    description: "Phase 5向けの画面構成メモ",
    status: "backlog",
    priority: "low",
    estimatedMinutes: 90,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task-backlog-2",
    projectId: "prj-client",
    title: "競合サービスの機能比較表",
    status: "backlog",
    priority: "medium",
    estimatedMinutes: 120,
    dueDate: "2026-09-18",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task-todo-1",
    projectId: "prj-hub",
    title: "TODOトレイのフィルタ仕様を固める",
    status: "todo",
    priority: "high",
    estimatedMinutes: 45,
    dueDate: "2026-09-08",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task-todo-2",
    projectId: "prj-ops",
    title: "週次レビュー用チェックリスト作成",
    status: "todo",
    priority: "medium",
    estimatedMinutes: 30,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task-todo-3",
    projectId: "prj-client",
    title: "提案資料のアウトライン",
    status: "todo",
    priority: "high",
    estimatedMinutes: 60,
    dueDate: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task-scheduled-1",
    projectId: "prj-hub",
    title: "型定義とモックデータの実装",
    status: "scheduled",
    priority: "high",
    estimatedMinutes: 90,
    scheduledDate: "2026-09-01",
    startTime: "21:00",
    endTime: "22:30",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task-scheduled-2",
    projectId: "prj-hub",
    title: "週間カレンダー枠のレイアウト",
    status: "in_progress",
    priority: "high",
    estimatedMinutes: 120,
    scheduledDate: "2026-09-05",
    startTime: "09:00",
    endTime: "11:00",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task-scheduled-3",
    projectId: "prj-client",
    title: "キックオフ議事メモ整理",
    status: "scheduled",
    priority: "medium",
    estimatedMinutes: 45,
    scheduledDate: "2026-09-03",
    startTime: "14:00",
    endTime: "14:45",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task-scheduled-4",
    projectId: "prj-ops",
    title: "夜間ルーティン：翌日の枠を確認",
    status: "scheduled",
    priority: "low",
    estimatedMinutes: 60,
    scheduledDate: "2026-09-05",
    startTime: "21:00",
    endTime: "22:00",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task-done-1",
    projectId: "prj-hub",
    title: "PRDの型定義を整理",
    status: "completed",
    priority: "medium",
    estimatedMinutes: 40,
    actualMinutes: 35,
    completedAt: "2026-09-04T11:20:00.000Z",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task-done-2",
    projectId: "prj-ops",
    title: "プロジェクトカラーの決定",
    status: "completed",
    priority: "low",
    estimatedMinutes: 20,
    actualMinutes: 15,
    completedAt: "2026-09-02T08:10:00.000Z",
    createdAt: now,
    updatedAt: now,
  },
];

export const mockMilestones: Milestone[] = [
  {
    id: "ms-phase-1",
    projectId: "prj-hub",
    title: "Phase 1 骨格",
    startDate: "2026-09-01",
    endDate: "2026-09-07",
    status: "in_progress",
  },
  {
    id: "ms-proposal",
    projectId: "prj-client",
    title: "初回提案提出",
    startDate: "2026-09-08",
    endDate: "2026-09-18",
    status: "planned",
  },
];

export function getProjectById(
  projectId: string,
  projects: Project[] = mockProjects,
): Project | undefined {
  return projects.find((project) => project.id === projectId);
}
